.PHONY: clean All

All:
	@echo "----------Building project:[ Pinga - Debug ]----------"
	@cd "Pinga" && "$(MAKE)" -f  "Pinga.mk"
clean:
	@echo "----------Cleaning project:[ Pinga - Debug ]----------"
	@cd "Pinga" && "$(MAKE)" -f  "Pinga.mk" clean
